//! Code generated by *./tools/gen-functions*. DO NOT EDIT.

#![allow(clippy::needless_lifetimes)]

use std::collections::BTreeMap;

use crate::functions::args::{ListRef, MapRef, Str, ValueRef};
use crate::functions::{Function, FunctionArg, FunctionArgs, FunctionReturn};
use crate::Value;

#[doc(hidden)]
impl<Func, R> Function<R, (Str,)> for Func
where
    Func: Fn(&str) -> R,
    R: FunctionReturn,

    (Str,): for<'a> FunctionArgs<Output<'a> = (&'a str,)>,
{
    fn call<'a>(&self, (a,): (&'a str,)) -> R {
        self(a)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (ListRef,)> for Func
where
    Func: Fn(&[Value]) -> R,
    R: FunctionReturn,

    (ListRef,): for<'a> FunctionArgs<Output<'a> = (&'a [Value],)>,
{
    fn call<'a>(&self, (a,): (&'a [Value],)) -> R {
        self(a)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (MapRef,)> for Func
where
    Func: Fn(&BTreeMap<String, Value>) -> R,
    R: FunctionReturn,

    (MapRef,): for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>,)>,
{
    fn call<'a>(&self, (a,): (&'a BTreeMap<String, Value>,)) -> R {
        self(a)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (ValueRef,)> for Func
where
    Func: Fn(&Value) -> R,
    R: FunctionReturn,

    (ValueRef,): for<'a> FunctionArgs<Output<'a> = (&'a Value,)>,
{
    fn call<'a>(&self, (a,): (&'a Value,)) -> R {
        self(a)
    }
}

#[doc(hidden)]
impl<Func, R, A> Function<R, (A, Str)> for Func
where
    Func: Fn(A, &str) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,

    (A, Str): for<'a> FunctionArgs<Output<'a> = (A, &'a str)>,
{
    fn call<'a>(&self, (a, b): (A, &'a str)) -> R {
        self(a, b)
    }
}

#[doc(hidden)]
impl<Func, R, B> Function<R, (Str, B)> for Func
where
    Func: Fn(&str, B) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,

    (Str, B): for<'a> FunctionArgs<Output<'a> = (&'a str, B)>,
{
    fn call<'a>(&self, (a, b): (&'a str, B)) -> R {
        self(a, b)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (Str, Str)> for Func
where
    Func: Fn(&str, &str) -> R,
    R: FunctionReturn,

    (Str, Str): for<'a> FunctionArgs<Output<'a> = (&'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b): (&'a str, &'a str)) -> R {
        self(a, b)
    }
}

#[doc(hidden)]
impl<Func, R, B> Function<R, (ListRef, B)> for Func
where
    Func: Fn(&[Value], B) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,

    (ListRef, B): for<'a> FunctionArgs<Output<'a> = (&'a [Value], B)>,
{
    fn call<'a>(&self, (a, b): (&'a [Value], B)) -> R {
        self(a, b)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (ListRef, Str)> for Func
where
    Func: Fn(&[Value], &str) -> R,
    R: FunctionReturn,

    (ListRef, Str): for<'a> FunctionArgs<Output<'a> = (&'a [Value], &'a str)>,
{
    fn call<'a>(&self, (a, b): (&'a [Value], &'a str)) -> R {
        self(a, b)
    }
}

#[doc(hidden)]
impl<Func, R, B> Function<R, (MapRef, B)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, B) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,

    (MapRef, B): for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, B)>,
{
    fn call<'a>(&self, (a, b): (&'a BTreeMap<String, Value>, B)) -> R {
        self(a, b)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (MapRef, Str)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, &str) -> R,
    R: FunctionReturn,

    (MapRef, Str): for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, &'a str)>,
{
    fn call<'a>(&self, (a, b): (&'a BTreeMap<String, Value>, &'a str)) -> R {
        self(a, b)
    }
}

#[doc(hidden)]
impl<Func, R, B> Function<R, (ValueRef, B)> for Func
where
    Func: Fn(&Value, B) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,

    (ValueRef, B): for<'a> FunctionArgs<Output<'a> = (&'a Value, B)>,
{
    fn call<'a>(&self, (a, b): (&'a Value, B)) -> R {
        self(a, b)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (ValueRef, Str)> for Func
where
    Func: Fn(&Value, &str) -> R,
    R: FunctionReturn,

    (ValueRef, Str): for<'a> FunctionArgs<Output<'a> = (&'a Value, &'a str)>,
{
    fn call<'a>(&self, (a, b): (&'a Value, &'a str)) -> R {
        self(a, b)
    }
}

#[doc(hidden)]
impl<Func, R, A, B> Function<R, (A, B, Str)> for Func
where
    Func: Fn(A, B, &str) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    B: for<'a> FunctionArg<Output<'a> = B>,

    (A, B, Str): for<'a> FunctionArgs<Output<'a> = (A, B, &'a str)>,
{
    fn call<'a>(&self, (a, b, c): (A, B, &'a str)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R, A, C> Function<R, (A, Str, C)> for Func
where
    Func: Fn(A, &str, C) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (A, Str, C): for<'a> FunctionArgs<Output<'a> = (A, &'a str, C)>,
{
    fn call<'a>(&self, (a, b, c): (A, &'a str, C)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R, A> Function<R, (A, Str, Str)> for Func
where
    Func: Fn(A, &str, &str) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,

    (A, Str, Str): for<'a> FunctionArgs<Output<'a> = (A, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c): (A, &'a str, &'a str)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R, B, C> Function<R, (Str, B, C)> for Func
where
    Func: Fn(&str, B, C) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (Str, B, C): for<'a> FunctionArgs<Output<'a> = (&'a str, B, C)>,
{
    fn call<'a>(&self, (a, b, c): (&'a str, B, C)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R, B> Function<R, (Str, B, Str)> for Func
where
    Func: Fn(&str, B, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,

    (Str, B, Str): for<'a> FunctionArgs<Output<'a> = (&'a str, B, &'a str)>,
{
    fn call<'a>(&self, (a, b, c): (&'a str, B, &'a str)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R, C> Function<R, (Str, Str, C)> for Func
where
    Func: Fn(&str, &str, C) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,

    (Str, Str, C): for<'a> FunctionArgs<Output<'a> = (&'a str, &'a str, C)>,
{
    fn call<'a>(&self, (a, b, c): (&'a str, &'a str, C)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (Str, Str, Str)> for Func
where
    Func: Fn(&str, &str, &str) -> R,
    R: FunctionReturn,

    (Str, Str, Str): for<'a> FunctionArgs<Output<'a> = (&'a str, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c): (&'a str, &'a str, &'a str)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R, B, C> Function<R, (ListRef, B, C)> for Func
where
    Func: Fn(&[Value], B, C) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (ListRef, B, C): for<'a> FunctionArgs<Output<'a> = (&'a [Value], B, C)>,
{
    fn call<'a>(&self, (a, b, c): (&'a [Value], B, C)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R, B> Function<R, (ListRef, B, Str)> for Func
where
    Func: Fn(&[Value], B, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,

    (ListRef, B, Str): for<'a> FunctionArgs<Output<'a> = (&'a [Value], B, &'a str)>,
{
    fn call<'a>(&self, (a, b, c): (&'a [Value], B, &'a str)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R, C> Function<R, (ListRef, Str, C)> for Func
where
    Func: Fn(&[Value], &str, C) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,

    (ListRef, Str, C): for<'a> FunctionArgs<Output<'a> = (&'a [Value], &'a str, C)>,
{
    fn call<'a>(&self, (a, b, c): (&'a [Value], &'a str, C)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (ListRef, Str, Str)> for Func
where
    Func: Fn(&[Value], &str, &str) -> R,
    R: FunctionReturn,

    (ListRef, Str, Str): for<'a> FunctionArgs<Output<'a> = (&'a [Value], &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c): (&'a [Value], &'a str, &'a str)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R, B, C> Function<R, (MapRef, B, C)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, B, C) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (MapRef, B, C): for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, B, C)>,
{
    fn call<'a>(&self, (a, b, c): (&'a BTreeMap<String, Value>, B, C)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R, B> Function<R, (MapRef, B, Str)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, B, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,

    (MapRef, B, Str): for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, B, &'a str)>,
{
    fn call<'a>(&self, (a, b, c): (&'a BTreeMap<String, Value>, B, &'a str)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R, C> Function<R, (MapRef, Str, C)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, &str, C) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,

    (MapRef, Str, C): for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, &'a str, C)>,
{
    fn call<'a>(&self, (a, b, c): (&'a BTreeMap<String, Value>, &'a str, C)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (MapRef, Str, Str)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, &str, &str) -> R,
    R: FunctionReturn,

    (MapRef, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c): (&'a BTreeMap<String, Value>, &'a str, &'a str)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R, B, C> Function<R, (ValueRef, B, C)> for Func
where
    Func: Fn(&Value, B, C) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (ValueRef, B, C): for<'a> FunctionArgs<Output<'a> = (&'a Value, B, C)>,
{
    fn call<'a>(&self, (a, b, c): (&'a Value, B, C)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R, B> Function<R, (ValueRef, B, Str)> for Func
where
    Func: Fn(&Value, B, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,

    (ValueRef, B, Str): for<'a> FunctionArgs<Output<'a> = (&'a Value, B, &'a str)>,
{
    fn call<'a>(&self, (a, b, c): (&'a Value, B, &'a str)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R, C> Function<R, (ValueRef, Str, C)> for Func
where
    Func: Fn(&Value, &str, C) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,

    (ValueRef, Str, C): for<'a> FunctionArgs<Output<'a> = (&'a Value, &'a str, C)>,
{
    fn call<'a>(&self, (a, b, c): (&'a Value, &'a str, C)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (ValueRef, Str, Str)> for Func
where
    Func: Fn(&Value, &str, &str) -> R,
    R: FunctionReturn,

    (ValueRef, Str, Str): for<'a> FunctionArgs<Output<'a> = (&'a Value, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c): (&'a Value, &'a str, &'a str)) -> R {
        self(a, b, c)
    }
}

#[doc(hidden)]
impl<Func, R, A, B, C> Function<R, (A, B, C, Str)> for Func
where
    Func: Fn(A, B, C, &str) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (A, B, C, Str): for<'a> FunctionArgs<Output<'a> = (A, B, C, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (A, B, C, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, A, B, D> Function<R, (A, B, Str, D)> for Func
where
    Func: Fn(A, B, &str, D) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    B: for<'a> FunctionArg<Output<'a> = B>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (A, B, Str, D): for<'a> FunctionArgs<Output<'a> = (A, B, &'a str, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (A, B, &'a str, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, A, B> Function<R, (A, B, Str, Str)> for Func
where
    Func: Fn(A, B, &str, &str) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    B: for<'a> FunctionArg<Output<'a> = B>,

    (A, B, Str, Str): for<'a> FunctionArgs<Output<'a> = (A, B, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (A, B, &'a str, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, A, C, D> Function<R, (A, Str, C, D)> for Func
where
    Func: Fn(A, &str, C, D) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (A, Str, C, D): for<'a> FunctionArgs<Output<'a> = (A, &'a str, C, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (A, &'a str, C, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, A, C> Function<R, (A, Str, C, Str)> for Func
where
    Func: Fn(A, &str, C, &str) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (A, Str, C, Str): for<'a> FunctionArgs<Output<'a> = (A, &'a str, C, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (A, &'a str, C, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, A, D> Function<R, (A, Str, Str, D)> for Func
where
    Func: Fn(A, &str, &str, D) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (A, Str, Str, D): for<'a> FunctionArgs<Output<'a> = (A, &'a str, &'a str, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (A, &'a str, &'a str, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, A> Function<R, (A, Str, Str, Str)> for Func
where
    Func: Fn(A, &str, &str, &str) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,

    (A, Str, Str, Str): for<'a> FunctionArgs<Output<'a> = (A, &'a str, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (A, &'a str, &'a str, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, B, C, D> Function<R, (Str, B, C, D)> for Func
where
    Func: Fn(&str, B, C, D) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (Str, B, C, D): for<'a> FunctionArgs<Output<'a> = (&'a str, B, C, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a str, B, C, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, B, C> Function<R, (Str, B, C, Str)> for Func
where
    Func: Fn(&str, B, C, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (Str, B, C, Str): for<'a> FunctionArgs<Output<'a> = (&'a str, B, C, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a str, B, C, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, B, D> Function<R, (Str, B, Str, D)> for Func
where
    Func: Fn(&str, B, &str, D) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (Str, B, Str, D): for<'a> FunctionArgs<Output<'a> = (&'a str, B, &'a str, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a str, B, &'a str, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, B> Function<R, (Str, B, Str, Str)> for Func
where
    Func: Fn(&str, B, &str, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,

    (Str, B, Str, Str): for<'a> FunctionArgs<Output<'a> = (&'a str, B, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a str, B, &'a str, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, C, D> Function<R, (Str, Str, C, D)> for Func
where
    Func: Fn(&str, &str, C, D) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (Str, Str, C, D): for<'a> FunctionArgs<Output<'a> = (&'a str, &'a str, C, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a str, &'a str, C, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, C> Function<R, (Str, Str, C, Str)> for Func
where
    Func: Fn(&str, &str, C, &str) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,

    (Str, Str, C, Str): for<'a> FunctionArgs<Output<'a> = (&'a str, &'a str, C, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a str, &'a str, C, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, D> Function<R, (Str, Str, Str, D)> for Func
where
    Func: Fn(&str, &str, &str, D) -> R,
    R: FunctionReturn,

    D: for<'a> FunctionArg<Output<'a> = D>,

    (Str, Str, Str, D): for<'a> FunctionArgs<Output<'a> = (&'a str, &'a str, &'a str, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a str, &'a str, &'a str, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (Str, Str, Str, Str)> for Func
where
    Func: Fn(&str, &str, &str, &str) -> R,
    R: FunctionReturn,

    (Str, Str, Str, Str): for<'a> FunctionArgs<Output<'a> = (&'a str, &'a str, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a str, &'a str, &'a str, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, B, C, D> Function<R, (ListRef, B, C, D)> for Func
where
    Func: Fn(&[Value], B, C, D) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (ListRef, B, C, D): for<'a> FunctionArgs<Output<'a> = (&'a [Value], B, C, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a [Value], B, C, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, B, C> Function<R, (ListRef, B, C, Str)> for Func
where
    Func: Fn(&[Value], B, C, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (ListRef, B, C, Str): for<'a> FunctionArgs<Output<'a> = (&'a [Value], B, C, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a [Value], B, C, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, B, D> Function<R, (ListRef, B, Str, D)> for Func
where
    Func: Fn(&[Value], B, &str, D) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (ListRef, B, Str, D): for<'a> FunctionArgs<Output<'a> = (&'a [Value], B, &'a str, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a [Value], B, &'a str, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, B> Function<R, (ListRef, B, Str, Str)> for Func
where
    Func: Fn(&[Value], B, &str, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,

    (ListRef, B, Str, Str): for<'a> FunctionArgs<Output<'a> = (&'a [Value], B, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a [Value], B, &'a str, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, C, D> Function<R, (ListRef, Str, C, D)> for Func
where
    Func: Fn(&[Value], &str, C, D) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (ListRef, Str, C, D): for<'a> FunctionArgs<Output<'a> = (&'a [Value], &'a str, C, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a [Value], &'a str, C, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, C> Function<R, (ListRef, Str, C, Str)> for Func
where
    Func: Fn(&[Value], &str, C, &str) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,

    (ListRef, Str, C, Str): for<'a> FunctionArgs<Output<'a> = (&'a [Value], &'a str, C, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a [Value], &'a str, C, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, D> Function<R, (ListRef, Str, Str, D)> for Func
where
    Func: Fn(&[Value], &str, &str, D) -> R,
    R: FunctionReturn,

    D: for<'a> FunctionArg<Output<'a> = D>,

    (ListRef, Str, Str, D): for<'a> FunctionArgs<Output<'a> = (&'a [Value], &'a str, &'a str, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a [Value], &'a str, &'a str, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (ListRef, Str, Str, Str)> for Func
where
    Func: Fn(&[Value], &str, &str, &str) -> R,
    R: FunctionReturn,

    (ListRef, Str, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a [Value], &'a str, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a [Value], &'a str, &'a str, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, B, C, D> Function<R, (MapRef, B, C, D)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, B, C, D) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (MapRef, B, C, D): for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, B, C, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a BTreeMap<String, Value>, B, C, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, B, C> Function<R, (MapRef, B, C, Str)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, B, C, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (MapRef, B, C, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, B, C, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a BTreeMap<String, Value>, B, C, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, B, D> Function<R, (MapRef, B, Str, D)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, B, &str, D) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (MapRef, B, Str, D):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, B, &'a str, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a BTreeMap<String, Value>, B, &'a str, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, B> Function<R, (MapRef, B, Str, Str)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, B, &str, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,

    (MapRef, B, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, B, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a BTreeMap<String, Value>, B, &'a str, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, C, D> Function<R, (MapRef, Str, C, D)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, &str, C, D) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (MapRef, Str, C, D):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, &'a str, C, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a BTreeMap<String, Value>, &'a str, C, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, C> Function<R, (MapRef, Str, C, Str)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, &str, C, &str) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,

    (MapRef, Str, C, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, &'a str, C, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a BTreeMap<String, Value>, &'a str, C, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, D> Function<R, (MapRef, Str, Str, D)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, &str, &str, D) -> R,
    R: FunctionReturn,

    D: for<'a> FunctionArg<Output<'a> = D>,

    (MapRef, Str, Str, D):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, &'a str, &'a str, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a BTreeMap<String, Value>, &'a str, &'a str, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (MapRef, Str, Str, Str)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, &str, &str, &str) -> R,
    R: FunctionReturn,

    (MapRef, Str, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, &'a str, &'a str, &'a str)>,
{
    fn call<'a>(
        &self,
        (a, b, c, d): (&'a BTreeMap<String, Value>, &'a str, &'a str, &'a str),
    ) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, B, C, D> Function<R, (ValueRef, B, C, D)> for Func
where
    Func: Fn(&Value, B, C, D) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (ValueRef, B, C, D): for<'a> FunctionArgs<Output<'a> = (&'a Value, B, C, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a Value, B, C, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, B, C> Function<R, (ValueRef, B, C, Str)> for Func
where
    Func: Fn(&Value, B, C, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (ValueRef, B, C, Str): for<'a> FunctionArgs<Output<'a> = (&'a Value, B, C, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a Value, B, C, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, B, D> Function<R, (ValueRef, B, Str, D)> for Func
where
    Func: Fn(&Value, B, &str, D) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (ValueRef, B, Str, D): for<'a> FunctionArgs<Output<'a> = (&'a Value, B, &'a str, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a Value, B, &'a str, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, B> Function<R, (ValueRef, B, Str, Str)> for Func
where
    Func: Fn(&Value, B, &str, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,

    (ValueRef, B, Str, Str): for<'a> FunctionArgs<Output<'a> = (&'a Value, B, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a Value, B, &'a str, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, C, D> Function<R, (ValueRef, Str, C, D)> for Func
where
    Func: Fn(&Value, &str, C, D) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (ValueRef, Str, C, D): for<'a> FunctionArgs<Output<'a> = (&'a Value, &'a str, C, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a Value, &'a str, C, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, C> Function<R, (ValueRef, Str, C, Str)> for Func
where
    Func: Fn(&Value, &str, C, &str) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,

    (ValueRef, Str, C, Str): for<'a> FunctionArgs<Output<'a> = (&'a Value, &'a str, C, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a Value, &'a str, C, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, D> Function<R, (ValueRef, Str, Str, D)> for Func
where
    Func: Fn(&Value, &str, &str, D) -> R,
    R: FunctionReturn,

    D: for<'a> FunctionArg<Output<'a> = D>,

    (ValueRef, Str, Str, D): for<'a> FunctionArgs<Output<'a> = (&'a Value, &'a str, &'a str, D)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a Value, &'a str, &'a str, D)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (ValueRef, Str, Str, Str)> for Func
where
    Func: Fn(&Value, &str, &str, &str) -> R,
    R: FunctionReturn,

    (ValueRef, Str, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a Value, &'a str, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d): (&'a Value, &'a str, &'a str, &'a str)) -> R {
        self(a, b, c, d)
    }
}

#[doc(hidden)]
impl<Func, R, A, B, C, D> Function<R, (A, B, C, D, Str)> for Func
where
    Func: Fn(A, B, C, D, &str) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (A, B, C, D, Str): for<'a> FunctionArgs<Output<'a> = (A, B, C, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (A, B, C, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, A, B, C, E> Function<R, (A, B, C, Str, E)> for Func
where
    Func: Fn(A, B, C, &str, E) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (A, B, C, Str, E): for<'a> FunctionArgs<Output<'a> = (A, B, C, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (A, B, C, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, A, B, C> Function<R, (A, B, C, Str, Str)> for Func
where
    Func: Fn(A, B, C, &str, &str) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (A, B, C, Str, Str): for<'a> FunctionArgs<Output<'a> = (A, B, C, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (A, B, C, &'a str, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, A, B, D, E> Function<R, (A, B, Str, D, E)> for Func
where
    Func: Fn(A, B, &str, D, E) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    B: for<'a> FunctionArg<Output<'a> = B>,
    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (A, B, Str, D, E): for<'a> FunctionArgs<Output<'a> = (A, B, &'a str, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (A, B, &'a str, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, A, B, D> Function<R, (A, B, Str, D, Str)> for Func
where
    Func: Fn(A, B, &str, D, &str) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    B: for<'a> FunctionArg<Output<'a> = B>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (A, B, Str, D, Str): for<'a> FunctionArgs<Output<'a> = (A, B, &'a str, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (A, B, &'a str, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, A, B, E> Function<R, (A, B, Str, Str, E)> for Func
where
    Func: Fn(A, B, &str, &str, E) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    B: for<'a> FunctionArg<Output<'a> = B>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (A, B, Str, Str, E): for<'a> FunctionArgs<Output<'a> = (A, B, &'a str, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (A, B, &'a str, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, A, B> Function<R, (A, B, Str, Str, Str)> for Func
where
    Func: Fn(A, B, &str, &str, &str) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    B: for<'a> FunctionArg<Output<'a> = B>,

    (A, B, Str, Str, Str): for<'a> FunctionArgs<Output<'a> = (A, B, &'a str, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (A, B, &'a str, &'a str, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, A, C, D, E> Function<R, (A, Str, C, D, E)> for Func
where
    Func: Fn(A, &str, C, D, E) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (A, Str, C, D, E): for<'a> FunctionArgs<Output<'a> = (A, &'a str, C, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (A, &'a str, C, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, A, C, D> Function<R, (A, Str, C, D, Str)> for Func
where
    Func: Fn(A, &str, C, D, &str) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (A, Str, C, D, Str): for<'a> FunctionArgs<Output<'a> = (A, &'a str, C, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (A, &'a str, C, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, A, C, E> Function<R, (A, Str, C, Str, E)> for Func
where
    Func: Fn(A, &str, C, &str, E) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (A, Str, C, Str, E): for<'a> FunctionArgs<Output<'a> = (A, &'a str, C, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (A, &'a str, C, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, A, C> Function<R, (A, Str, C, Str, Str)> for Func
where
    Func: Fn(A, &str, C, &str, &str) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (A, Str, C, Str, Str): for<'a> FunctionArgs<Output<'a> = (A, &'a str, C, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (A, &'a str, C, &'a str, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, A, D, E> Function<R, (A, Str, Str, D, E)> for Func
where
    Func: Fn(A, &str, &str, D, E) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (A, Str, Str, D, E): for<'a> FunctionArgs<Output<'a> = (A, &'a str, &'a str, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (A, &'a str, &'a str, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, A, D> Function<R, (A, Str, Str, D, Str)> for Func
where
    Func: Fn(A, &str, &str, D, &str) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (A, Str, Str, D, Str): for<'a> FunctionArgs<Output<'a> = (A, &'a str, &'a str, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (A, &'a str, &'a str, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, A, E> Function<R, (A, Str, Str, Str, E)> for Func
where
    Func: Fn(A, &str, &str, &str, E) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (A, Str, Str, Str, E): for<'a> FunctionArgs<Output<'a> = (A, &'a str, &'a str, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (A, &'a str, &'a str, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, A> Function<R, (A, Str, Str, Str, Str)> for Func
where
    Func: Fn(A, &str, &str, &str, &str) -> R,
    R: FunctionReturn,

    A: for<'a> FunctionArg<Output<'a> = A>,

    (A, Str, Str, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (A, &'a str, &'a str, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (A, &'a str, &'a str, &'a str, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, C, D, E> Function<R, (Str, B, C, D, E)> for Func
where
    Func: Fn(&str, B, C, D, E) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (Str, B, C, D, E): for<'a> FunctionArgs<Output<'a> = (&'a str, B, C, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a str, B, C, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, C, D> Function<R, (Str, B, C, D, Str)> for Func
where
    Func: Fn(&str, B, C, D, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (Str, B, C, D, Str): for<'a> FunctionArgs<Output<'a> = (&'a str, B, C, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a str, B, C, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, C, E> Function<R, (Str, B, C, Str, E)> for Func
where
    Func: Fn(&str, B, C, &str, E) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (Str, B, C, Str, E): for<'a> FunctionArgs<Output<'a> = (&'a str, B, C, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a str, B, C, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, C> Function<R, (Str, B, C, Str, Str)> for Func
where
    Func: Fn(&str, B, C, &str, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (Str, B, C, Str, Str): for<'a> FunctionArgs<Output<'a> = (&'a str, B, C, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a str, B, C, &'a str, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, D, E> Function<R, (Str, B, Str, D, E)> for Func
where
    Func: Fn(&str, B, &str, D, E) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (Str, B, Str, D, E): for<'a> FunctionArgs<Output<'a> = (&'a str, B, &'a str, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a str, B, &'a str, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, D> Function<R, (Str, B, Str, D, Str)> for Func
where
    Func: Fn(&str, B, &str, D, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (Str, B, Str, D, Str): for<'a> FunctionArgs<Output<'a> = (&'a str, B, &'a str, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a str, B, &'a str, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, E> Function<R, (Str, B, Str, Str, E)> for Func
where
    Func: Fn(&str, B, &str, &str, E) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (Str, B, Str, Str, E): for<'a> FunctionArgs<Output<'a> = (&'a str, B, &'a str, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a str, B, &'a str, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B> Function<R, (Str, B, Str, Str, Str)> for Func
where
    Func: Fn(&str, B, &str, &str, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,

    (Str, B, Str, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a str, B, &'a str, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a str, B, &'a str, &'a str, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, C, D, E> Function<R, (Str, Str, C, D, E)> for Func
where
    Func: Fn(&str, &str, C, D, E) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (Str, Str, C, D, E): for<'a> FunctionArgs<Output<'a> = (&'a str, &'a str, C, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a str, &'a str, C, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, C, D> Function<R, (Str, Str, C, D, Str)> for Func
where
    Func: Fn(&str, &str, C, D, &str) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (Str, Str, C, D, Str): for<'a> FunctionArgs<Output<'a> = (&'a str, &'a str, C, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a str, &'a str, C, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, C, E> Function<R, (Str, Str, C, Str, E)> for Func
where
    Func: Fn(&str, &str, C, &str, E) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (Str, Str, C, Str, E): for<'a> FunctionArgs<Output<'a> = (&'a str, &'a str, C, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a str, &'a str, C, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, C> Function<R, (Str, Str, C, Str, Str)> for Func
where
    Func: Fn(&str, &str, C, &str, &str) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,

    (Str, Str, C, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a str, &'a str, C, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a str, &'a str, C, &'a str, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, D, E> Function<R, (Str, Str, Str, D, E)> for Func
where
    Func: Fn(&str, &str, &str, D, E) -> R,
    R: FunctionReturn,

    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (Str, Str, Str, D, E): for<'a> FunctionArgs<Output<'a> = (&'a str, &'a str, &'a str, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a str, &'a str, &'a str, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, D> Function<R, (Str, Str, Str, D, Str)> for Func
where
    Func: Fn(&str, &str, &str, D, &str) -> R,
    R: FunctionReturn,

    D: for<'a> FunctionArg<Output<'a> = D>,

    (Str, Str, Str, D, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a str, &'a str, &'a str, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a str, &'a str, &'a str, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, E> Function<R, (Str, Str, Str, Str, E)> for Func
where
    Func: Fn(&str, &str, &str, &str, E) -> R,
    R: FunctionReturn,

    E: for<'a> FunctionArg<Output<'a> = E>,

    (Str, Str, Str, Str, E):
        for<'a> FunctionArgs<Output<'a> = (&'a str, &'a str, &'a str, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a str, &'a str, &'a str, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (Str, Str, Str, Str, Str)> for Func
where
    Func: Fn(&str, &str, &str, &str, &str) -> R,
    R: FunctionReturn,

    (Str, Str, Str, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a str, &'a str, &'a str, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a str, &'a str, &'a str, &'a str, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, C, D, E> Function<R, (ListRef, B, C, D, E)> for Func
where
    Func: Fn(&[Value], B, C, D, E) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (ListRef, B, C, D, E): for<'a> FunctionArgs<Output<'a> = (&'a [Value], B, C, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a [Value], B, C, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, C, D> Function<R, (ListRef, B, C, D, Str)> for Func
where
    Func: Fn(&[Value], B, C, D, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (ListRef, B, C, D, Str): for<'a> FunctionArgs<Output<'a> = (&'a [Value], B, C, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a [Value], B, C, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, C, E> Function<R, (ListRef, B, C, Str, E)> for Func
where
    Func: Fn(&[Value], B, C, &str, E) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (ListRef, B, C, Str, E): for<'a> FunctionArgs<Output<'a> = (&'a [Value], B, C, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a [Value], B, C, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, C> Function<R, (ListRef, B, C, Str, Str)> for Func
where
    Func: Fn(&[Value], B, C, &str, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (ListRef, B, C, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a [Value], B, C, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a [Value], B, C, &'a str, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, D, E> Function<R, (ListRef, B, Str, D, E)> for Func
where
    Func: Fn(&[Value], B, &str, D, E) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (ListRef, B, Str, D, E): for<'a> FunctionArgs<Output<'a> = (&'a [Value], B, &'a str, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a [Value], B, &'a str, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, D> Function<R, (ListRef, B, Str, D, Str)> for Func
where
    Func: Fn(&[Value], B, &str, D, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (ListRef, B, Str, D, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a [Value], B, &'a str, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a [Value], B, &'a str, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, E> Function<R, (ListRef, B, Str, Str, E)> for Func
where
    Func: Fn(&[Value], B, &str, &str, E) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (ListRef, B, Str, Str, E):
        for<'a> FunctionArgs<Output<'a> = (&'a [Value], B, &'a str, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a [Value], B, &'a str, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B> Function<R, (ListRef, B, Str, Str, Str)> for Func
where
    Func: Fn(&[Value], B, &str, &str, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,

    (ListRef, B, Str, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a [Value], B, &'a str, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a [Value], B, &'a str, &'a str, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, C, D, E> Function<R, (ListRef, Str, C, D, E)> for Func
where
    Func: Fn(&[Value], &str, C, D, E) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (ListRef, Str, C, D, E): for<'a> FunctionArgs<Output<'a> = (&'a [Value], &'a str, C, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a [Value], &'a str, C, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, C, D> Function<R, (ListRef, Str, C, D, Str)> for Func
where
    Func: Fn(&[Value], &str, C, D, &str) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (ListRef, Str, C, D, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a [Value], &'a str, C, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a [Value], &'a str, C, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, C, E> Function<R, (ListRef, Str, C, Str, E)> for Func
where
    Func: Fn(&[Value], &str, C, &str, E) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (ListRef, Str, C, Str, E):
        for<'a> FunctionArgs<Output<'a> = (&'a [Value], &'a str, C, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a [Value], &'a str, C, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, C> Function<R, (ListRef, Str, C, Str, Str)> for Func
where
    Func: Fn(&[Value], &str, C, &str, &str) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,

    (ListRef, Str, C, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a [Value], &'a str, C, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a [Value], &'a str, C, &'a str, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, D, E> Function<R, (ListRef, Str, Str, D, E)> for Func
where
    Func: Fn(&[Value], &str, &str, D, E) -> R,
    R: FunctionReturn,

    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (ListRef, Str, Str, D, E):
        for<'a> FunctionArgs<Output<'a> = (&'a [Value], &'a str, &'a str, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a [Value], &'a str, &'a str, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, D> Function<R, (ListRef, Str, Str, D, Str)> for Func
where
    Func: Fn(&[Value], &str, &str, D, &str) -> R,
    R: FunctionReturn,

    D: for<'a> FunctionArg<Output<'a> = D>,

    (ListRef, Str, Str, D, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a [Value], &'a str, &'a str, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a [Value], &'a str, &'a str, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, E> Function<R, (ListRef, Str, Str, Str, E)> for Func
where
    Func: Fn(&[Value], &str, &str, &str, E) -> R,
    R: FunctionReturn,

    E: for<'a> FunctionArg<Output<'a> = E>,

    (ListRef, Str, Str, Str, E):
        for<'a> FunctionArgs<Output<'a> = (&'a [Value], &'a str, &'a str, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a [Value], &'a str, &'a str, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (ListRef, Str, Str, Str, Str)> for Func
where
    Func: Fn(&[Value], &str, &str, &str, &str) -> R,
    R: FunctionReturn,

    (ListRef, Str, Str, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a [Value], &'a str, &'a str, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a [Value], &'a str, &'a str, &'a str, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, C, D, E> Function<R, (MapRef, B, C, D, E)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, B, C, D, E) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (MapRef, B, C, D, E):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, B, C, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a BTreeMap<String, Value>, B, C, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, C, D> Function<R, (MapRef, B, C, D, Str)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, B, C, D, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (MapRef, B, C, D, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, B, C, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a BTreeMap<String, Value>, B, C, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, C, E> Function<R, (MapRef, B, C, Str, E)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, B, C, &str, E) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (MapRef, B, C, Str, E):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, B, C, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a BTreeMap<String, Value>, B, C, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, C> Function<R, (MapRef, B, C, Str, Str)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, B, C, &str, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (MapRef, B, C, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, B, C, &'a str, &'a str)>,
{
    fn call<'a>(
        &self,
        (a, b, c, d, e): (&'a BTreeMap<String, Value>, B, C, &'a str, &'a str),
    ) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, D, E> Function<R, (MapRef, B, Str, D, E)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, B, &str, D, E) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (MapRef, B, Str, D, E):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, B, &'a str, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a BTreeMap<String, Value>, B, &'a str, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, D> Function<R, (MapRef, B, Str, D, Str)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, B, &str, D, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (MapRef, B, Str, D, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, B, &'a str, D, &'a str)>,
{
    fn call<'a>(
        &self,
        (a, b, c, d, e): (&'a BTreeMap<String, Value>, B, &'a str, D, &'a str),
    ) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, E> Function<R, (MapRef, B, Str, Str, E)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, B, &str, &str, E) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (MapRef, B, Str, Str, E):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, B, &'a str, &'a str, E)>,
{
    fn call<'a>(
        &self,
        (a, b, c, d, e): (&'a BTreeMap<String, Value>, B, &'a str, &'a str, E),
    ) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B> Function<R, (MapRef, B, Str, Str, Str)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, B, &str, &str, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,

    (MapRef, B, Str, Str, Str): for<'a> FunctionArgs<
        Output<'a> = (&'a BTreeMap<String, Value>, B, &'a str, &'a str, &'a str),
    >,
{
    fn call<'a>(
        &self,
        (a, b, c, d, e): (&'a BTreeMap<String, Value>, B, &'a str, &'a str, &'a str),
    ) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, C, D, E> Function<R, (MapRef, Str, C, D, E)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, &str, C, D, E) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (MapRef, Str, C, D, E):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, &'a str, C, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a BTreeMap<String, Value>, &'a str, C, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, C, D> Function<R, (MapRef, Str, C, D, Str)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, &str, C, D, &str) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (MapRef, Str, C, D, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, &'a str, C, D, &'a str)>,
{
    fn call<'a>(
        &self,
        (a, b, c, d, e): (&'a BTreeMap<String, Value>, &'a str, C, D, &'a str),
    ) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, C, E> Function<R, (MapRef, Str, C, Str, E)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, &str, C, &str, E) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (MapRef, Str, C, Str, E):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, &'a str, C, &'a str, E)>,
{
    fn call<'a>(
        &self,
        (a, b, c, d, e): (&'a BTreeMap<String, Value>, &'a str, C, &'a str, E),
    ) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, C> Function<R, (MapRef, Str, C, Str, Str)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, &str, C, &str, &str) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,

    (MapRef, Str, C, Str, Str): for<'a> FunctionArgs<
        Output<'a> = (&'a BTreeMap<String, Value>, &'a str, C, &'a str, &'a str),
    >,
{
    fn call<'a>(
        &self,
        (a, b, c, d, e): (&'a BTreeMap<String, Value>, &'a str, C, &'a str, &'a str),
    ) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, D, E> Function<R, (MapRef, Str, Str, D, E)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, &str, &str, D, E) -> R,
    R: FunctionReturn,

    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (MapRef, Str, Str, D, E):
        for<'a> FunctionArgs<Output<'a> = (&'a BTreeMap<String, Value>, &'a str, &'a str, D, E)>,
{
    fn call<'a>(
        &self,
        (a, b, c, d, e): (&'a BTreeMap<String, Value>, &'a str, &'a str, D, E),
    ) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, D> Function<R, (MapRef, Str, Str, D, Str)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, &str, &str, D, &str) -> R,
    R: FunctionReturn,

    D: for<'a> FunctionArg<Output<'a> = D>,

    (MapRef, Str, Str, D, Str): for<'a> FunctionArgs<
        Output<'a> = (&'a BTreeMap<String, Value>, &'a str, &'a str, D, &'a str),
    >,
{
    fn call<'a>(
        &self,
        (a, b, c, d, e): (&'a BTreeMap<String, Value>, &'a str, &'a str, D, &'a str),
    ) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, E> Function<R, (MapRef, Str, Str, Str, E)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, &str, &str, &str, E) -> R,
    R: FunctionReturn,

    E: for<'a> FunctionArg<Output<'a> = E>,

    (MapRef, Str, Str, Str, E): for<'a> FunctionArgs<
        Output<'a> = (&'a BTreeMap<String, Value>, &'a str, &'a str, &'a str, E),
    >,
{
    fn call<'a>(
        &self,
        (a, b, c, d, e): (&'a BTreeMap<String, Value>, &'a str, &'a str, &'a str, E),
    ) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (MapRef, Str, Str, Str, Str)> for Func
where
    Func: Fn(&BTreeMap<String, Value>, &str, &str, &str, &str) -> R,
    R: FunctionReturn,

    (MapRef, Str, Str, Str, Str): for<'a> FunctionArgs<
        Output<'a> = (
            &'a BTreeMap<String, Value>,
            &'a str,
            &'a str,
            &'a str,
            &'a str,
        ),
    >,
{
    fn call<'a>(
        &self,
        (a, b, c, d, e): (
            &'a BTreeMap<String, Value>,
            &'a str,
            &'a str,
            &'a str,
            &'a str,
        ),
    ) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, C, D, E> Function<R, (ValueRef, B, C, D, E)> for Func
where
    Func: Fn(&Value, B, C, D, E) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (ValueRef, B, C, D, E): for<'a> FunctionArgs<Output<'a> = (&'a Value, B, C, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a Value, B, C, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, C, D> Function<R, (ValueRef, B, C, D, Str)> for Func
where
    Func: Fn(&Value, B, C, D, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (ValueRef, B, C, D, Str): for<'a> FunctionArgs<Output<'a> = (&'a Value, B, C, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a Value, B, C, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, C, E> Function<R, (ValueRef, B, C, Str, E)> for Func
where
    Func: Fn(&Value, B, C, &str, E) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (ValueRef, B, C, Str, E): for<'a> FunctionArgs<Output<'a> = (&'a Value, B, C, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a Value, B, C, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, C> Function<R, (ValueRef, B, C, Str, Str)> for Func
where
    Func: Fn(&Value, B, C, &str, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    C: for<'a> FunctionArg<Output<'a> = C>,

    (ValueRef, B, C, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a Value, B, C, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a Value, B, C, &'a str, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, D, E> Function<R, (ValueRef, B, Str, D, E)> for Func
where
    Func: Fn(&Value, B, &str, D, E) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (ValueRef, B, Str, D, E): for<'a> FunctionArgs<Output<'a> = (&'a Value, B, &'a str, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a Value, B, &'a str, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, D> Function<R, (ValueRef, B, Str, D, Str)> for Func
where
    Func: Fn(&Value, B, &str, D, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (ValueRef, B, Str, D, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a Value, B, &'a str, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a Value, B, &'a str, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B, E> Function<R, (ValueRef, B, Str, Str, E)> for Func
where
    Func: Fn(&Value, B, &str, &str, E) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (ValueRef, B, Str, Str, E):
        for<'a> FunctionArgs<Output<'a> = (&'a Value, B, &'a str, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a Value, B, &'a str, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, B> Function<R, (ValueRef, B, Str, Str, Str)> for Func
where
    Func: Fn(&Value, B, &str, &str, &str) -> R,
    R: FunctionReturn,

    B: for<'a> FunctionArg<Output<'a> = B>,

    (ValueRef, B, Str, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a Value, B, &'a str, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a Value, B, &'a str, &'a str, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, C, D, E> Function<R, (ValueRef, Str, C, D, E)> for Func
where
    Func: Fn(&Value, &str, C, D, E) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (ValueRef, Str, C, D, E): for<'a> FunctionArgs<Output<'a> = (&'a Value, &'a str, C, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a Value, &'a str, C, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, C, D> Function<R, (ValueRef, Str, C, D, Str)> for Func
where
    Func: Fn(&Value, &str, C, D, &str) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,
    D: for<'a> FunctionArg<Output<'a> = D>,

    (ValueRef, Str, C, D, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a Value, &'a str, C, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a Value, &'a str, C, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, C, E> Function<R, (ValueRef, Str, C, Str, E)> for Func
where
    Func: Fn(&Value, &str, C, &str, E) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (ValueRef, Str, C, Str, E):
        for<'a> FunctionArgs<Output<'a> = (&'a Value, &'a str, C, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a Value, &'a str, C, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, C> Function<R, (ValueRef, Str, C, Str, Str)> for Func
where
    Func: Fn(&Value, &str, C, &str, &str) -> R,
    R: FunctionReturn,

    C: for<'a> FunctionArg<Output<'a> = C>,

    (ValueRef, Str, C, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a Value, &'a str, C, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a Value, &'a str, C, &'a str, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, D, E> Function<R, (ValueRef, Str, Str, D, E)> for Func
where
    Func: Fn(&Value, &str, &str, D, E) -> R,
    R: FunctionReturn,

    D: for<'a> FunctionArg<Output<'a> = D>,
    E: for<'a> FunctionArg<Output<'a> = E>,

    (ValueRef, Str, Str, D, E):
        for<'a> FunctionArgs<Output<'a> = (&'a Value, &'a str, &'a str, D, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a Value, &'a str, &'a str, D, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, D> Function<R, (ValueRef, Str, Str, D, Str)> for Func
where
    Func: Fn(&Value, &str, &str, D, &str) -> R,
    R: FunctionReturn,

    D: for<'a> FunctionArg<Output<'a> = D>,

    (ValueRef, Str, Str, D, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a Value, &'a str, &'a str, D, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a Value, &'a str, &'a str, D, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R, E> Function<R, (ValueRef, Str, Str, Str, E)> for Func
where
    Func: Fn(&Value, &str, &str, &str, E) -> R,
    R: FunctionReturn,

    E: for<'a> FunctionArg<Output<'a> = E>,

    (ValueRef, Str, Str, Str, E):
        for<'a> FunctionArgs<Output<'a> = (&'a Value, &'a str, &'a str, &'a str, E)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a Value, &'a str, &'a str, &'a str, E)) -> R {
        self(a, b, c, d, e)
    }
}

#[doc(hidden)]
impl<Func, R> Function<R, (ValueRef, Str, Str, Str, Str)> for Func
where
    Func: Fn(&Value, &str, &str, &str, &str) -> R,
    R: FunctionReturn,

    (ValueRef, Str, Str, Str, Str):
        for<'a> FunctionArgs<Output<'a> = (&'a Value, &'a str, &'a str, &'a str, &'a str)>,
{
    fn call<'a>(&self, (a, b, c, d, e): (&'a Value, &'a str, &'a str, &'a str, &'a str)) -> R {
        self(a, b, c, d, e)
    }
}
